@url = http://localhost:8080/api/alias

GET {{url}} HTTP/1.1

###

GET {{url}}/1 HTTP/1.1

###

POST http://localhost:8080/api/alias HTTP/1/1
Content-Type: application/json

{
    "name": "Test2",
    "persona": "T",
    "agentId": "2"
}

###

PUT {{url}}/1 HTTP/1.1
Content-Type: application/json

{
    "alias_id": "1",
    "name": "Test",
    "persona": "T",
    "agent_id": "2"
}

###

DELETE {{url}}/1 HTTP/1.1